### ISSUE TITLE
Only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by blake-regalia** [CrabDude/babel-node-debug#14]
Cannot debug a module that requires babel-polyfill:

```
throw new Error("only one instance of babel-polyfill is allowed");
  ^

Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (/..../node_modules/babel-polyfill/lib/index.js:8:9)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-node-debug/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (volt.js:1:1)
    at Module._compile (module.js:425:26)
```

**Comment by jtal** [comment]
@blake-regalia did you find a work around?
