### ISSUE TITLE
It fails on install

### ISSUE THREAD

**Issue by ChrisCinelli** [CrabDude/babel-node-debug#17]
```
$ npm install -g babel-node-debug

> v8-profiler@5.6.3 preinstall /Users/chris/.nvm/versions/node/v4.2.3/lib/node_modules/.staging/v8-profiler-1a869fbb
> npm install node-pre-gyp

/Users/chris/.nvm/versions/node/v4.2.3/bin/node-pre-gyp -> /Users/chris/.nvm/versions/node/v4.2.3/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
/Users/chris/.nvm/versions/node/v4.2.3/lib
└── node-pre-gyp@0.6.28


> v8-debug@0.7.7 preinstall /Users/chris/.nvm/versions/node/v4.2.3/lib/node_modules/.staging/v8-debug-417c0279
> node -e 'process.exit(0)'

/Users/chris/.nvm/versions/node/v4.2.3/lib
└── (empty)

npm ERR! Darwin 13.4.0
npm ERR! argv "/Users/chris/.nvm/versions/node/v4.2.3/bin/node" "/Users/chris/.nvm/versions/node/v4.2.3/bin/npm" "install" "-g" "babel-node-debug"
npm ERR! node v4.2.3
npm ERR! npm  v3.8.1
npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn sh

npm ERR! v8-debug@0.7.7 preinstall: `node -e 'process.exit(0)'`
npm ERR! spawn sh ENOENT
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 preinstall script 'node -e 'process.exit(0)''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e 'process.exit(0)'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chris/sws/npm-debug.log
npm ERR! code 1
```

**Comment by CrabDude** [comment]
I'll take a look.

**Comment by tomsvogel** [comment]
same Problem here, with node > 7 also node 8

**Comment by erlaveri** [comment]
The same issue.
```
$ sudo npm install -g babel-node-debug

> v8-profiler@5.6.5 preinstall /usr/lib/node_modules/babel-node-debug/node_modules/v8-profiler
> node -e 'process.exit(0)'


> v8-debug@0.7.7 preinstall /usr/lib/node_modules/babel-node-debug/node_modules/v8-debug
> node -e 'process.exit(0)'

/usr/bin/bode-debug -> /usr/lib/node_modules/babel-node-debug/bin/bode-debug.js
/usr/bin/babel-node-debug -> /usr/lib/node_modules/babel-node-debug/bin/bode-debug.js

> v8-debug@0.7.7 install /usr/lib/node_modules/babel-node-debug/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@8.9.4 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@8.9.4 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/babel-node-debug/node_modules/v8-debug/build'
gyp ERR! System Linux 4.13.0-26-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64/debug.node" "--module_name=debug" "--module_path=/usr/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64"
gyp ERR! cwd /usr/lib/node_modules/babel-node-debug/node_modules/v8-debug
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64/debug.node --module_name=debug --module_path=/usr/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/babel-node-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.13.0-26-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/babel-node-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/babel-node-debug/node_modules/v8-debug
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64/debug.node --module_name=debug --module_path=/usr/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64' (1)
gyp ERR! configure error stall: info lifecycle v8-debug@0.7.7~install: Failed to exec install script
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/babel-node-debug/node_modules/v8-debug'
gyp ERR! System Linux 4.13.0-26-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64/debug.node" "--module_name=debug" "--module_path=/usr/lib/node_modules/babel-node-debug/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64"
gyp ERR! cwd /usr/lib/node_modules/babel-node-debug/node_modules/v8-debug
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/babel-node-debug/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rtee/.npm/_logs/2018-01-12T22_03_40_206Z-debug.log
```

**Comment by CrabDude** [comment]
Unfortunately, I don't anticipate being able to work on this anytime in the near future.
