### ISSUE TITLE
TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by kolodny** [CrabDude/babel-node-debug#9]
Here's what my setup looks like:

``` json
{
  "presets": ["react", "es2015"],
  "env": {
    "development": {
      "presets": ["react-hmre"]
    }
  }
}
```

``` js
debugger;
console.log('test');
```

and the full dump

```

Debugger listening on port 5858
/Users/moshe/.nvm/versions/node/v5.1.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/Users/moshe/.nvm/versions/node/v5.1.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/Users/moshe/.nvm/versions/node/v5.1.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/moshe/.nvm/versions/node/v5.1.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/moshe/.nvm/versions/node/v5.1.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/Users/moshe/.nvm/versions/node/v5.1.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/Users/moshe/.nvm/versions/node/v5.1.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/moshe/.nvm/versions/node/v5.1.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
```

**Comment by chrisvasz** [comment]
I'm encountering the same error without the react-hmre development preset.

**Comment by kolodny** [comment]
yeah, I meant to remove that line, upon further investigation it appears that this module uses babel 5 and therefore will try to use an invalid `.babelrc` file. I spent some time getting this to work with babel 6 but haven't had any success

**Comment by CrabDude** [comment]
Yes. This is not currently compatible with babel@6, but there's high demand. I'm going to try to update it sometime next week.

**Comment by shaunc** [comment]
+1 ... any workaround for the moment?

**Comment by CrabDude** [comment]
If possible, please verify if the [PR](https://github.com/CrabDude/babel-node-debug/pull/12/) fixes the issue.

**Comment by CrabDude** [comment]
[Happy coding. :smiley: ](https://github.com/crabdude/babel-node-debug/compare/99c6b927d78009ce0a4d65e1e96e79177651fda2...36cbc72f8d6081d32b5890027113dd9bf15bd2ca)
